sa_array:
  - name: example-main-1
    sku: Standard_LRS
    kind: BlobStorage
    accessTier: Cool
    location: eastus
  - name: example-main-2
    sku: Standard_GRS
    kind: BlobStorage
    accessTier: Cool
    location: eastus
